



class RoverParams :

    THRESHOLD_GO_FORWARD      = 500
    THRESHOLD_GO_FORWARD_FULL = 800
    THRESHOLD_STOP_FORWARD  = 50
    OFFSET_WALL_LEFT = 0

    THRESHOLD_ROCK_FOUND = 20

    CRUISE_SPEED = 1.5
    APPROACH_SPEED = 1.5

    NAVIGATION_SAMPLE_TIME = 2.0
    NAVIGATION_DIST_THRESHOLD = 1.
    NAVIGATION_TIMEOUT = 10.

    ESCAPE_BLOCK_TIME = 1.

    PICK_ROCK_TIMEOUT = 2.